version: '2'
services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_CONFIG_URL=
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://192.168.99.2:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
      - BUILDBOT_ENV_WORKER_PASS=${BUILDBOT_ENV_WORKER_PASS}
    volumes:
      - ..:/var/lib/buildbot
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"
      - "9989:9989"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    expose:
      - 5432

  worker:
    image: "buildbot/buildbot-worker:master"
    environment:
      BUILDMASTER: buildbot
      BUILDMASTER_PORT: 9989
      WORKERNAME: worker-example
      WORKERPASS: ${BUILDBOT_ENV_WORKER_PASS}
      WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
      - buildbot
